### PR TITLE
added channel button

### PR DESCRIPTION
**Pull request by abhaymathur21**
Addresses issue #152

### CODE REVIEW

**Comment by abhaymathur21** [comment]
image

The drop down for channel types has been added

- still have to integrate the add channel form submit button
- still have to convert the add channel form to a popup

**Comment by abhaymathur21** [comment]
image
have finished integrating it and converting it to a popup

**Comment by abhaymathur21** [comment]
image
updated interface with updated variable names

**Comment by abhaymathur21** [comment]
image
this is what it looks like on the homepage

**Comment by abhaymathur21** [comment]
@shreypandey what ui feature should i move forward with next?

**Comment by KaranrajM** [comment]
Closing this PR as it is no longer needed and the other PR fixing this issue is merged successfully

**Pull request closed without merging**
