### PR TITLE
Added Bot Settings page and UI changes

### PR DESCRIPTION
**Pull request by vikash1810**
Fixes Issue #176  

## Changelog:

- Added BotSettings page with the following features:
  - Modify Bot credentials
  - Create new channels
  - Update Existing channel configuration and status
  - image

- Added confirmation model
  - image

- UI changes in settings model
  - image

### CODE REVIEW

**Comment by Lekhanrao** [comment]
@shreypandey, could you please take a look at this? After that we could close Issue #176 and #152

**Comment by KaranrajM** [comment]
Hi @vikash1810 I have reviewed the UI changes. I have a couple of thoughts to share here:

1. The activate (play) button still always shows the input popup box for whatsapp credentials. Instead of that popup, can we redirect to the new settings tab for the appropriate bot's channel activation if possible?
2. Can we autopopulate the url for pinnacle_whatsapp and telegram channel if possible cause I feel they wont change?
3. Also can we update the documentation for setting up the bot using this new UI?

Rest of the UI looks very good. Please let me know your thoughts on these changes.

**Comment by vikash1810** [comment]
Hi @KaranrajM, thanks for reviewing the pull request. 
The suggestions make perfect sense, I'll make the changes as mentioned.

**Comment by vikash1810** [comment]
Hi @KaranrajM, I've included the suggested changes in the latest commit.

**Comment by KaranrajM** [comment]
> Hi @KaranrajM, I've included the suggested changes in the latest commit.

Hi @vikash1810 the changes look good along with the documentation. I think we can go ahead and merge it.

**Pull request merged**
